//@ui5-bundle classification/Component-preload.js
sap.ui.require.preload({
	"classification/Component.js":function(){
sap.ui.define(["sap/fe/core/AppComponent"],function(e){"use strict";return e.extend("classification.Component",{metadata:{manifest:"json"}})});
},
	"classification/i18n/i18n.properties":'# This is the resource bundle for classification\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Route Classification\n\n#YDES: Application description\nappDescription=An SAP Fiori application.',
	"classification/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"classification","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:lrop","version":"1.18.0","toolsId":"69b8e286-dad1-495e-a999-5a52720f3117"},"dataSources":{"mainService":{"uri":"/odata/v4/route-classification/","type":"OData","settings":{"annotations":[],"odataVersion":"4.0"}}},"crossNavigation":{"inbounds":{"display":{"semanticObject":"classification","action":"display","title":"Route Classification","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.136.1","libs":{"sap.m":{},"sap.ui.core":{},"sap.fe.templates":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"classification.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"operationMode":"Server","autoExpandSelect":true,"earlyRequests":true}},"@i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"}},"resources":{"css":[]},"routing":{"config":{},"routes":[{"pattern":":?query:","name":"CustomerArticleSummaryList","target":"CustomerArticleSummaryList"},{"pattern":"CustomerArticleSummary({key}):?query:","name":"CustomerArticleSummaryObjectPage","target":"CustomerArticleSummaryObjectPage"}],"targets":{"CustomerArticleSummaryList":{"type":"Component","id":"CustomerArticleSummaryList","name":"sap.fe.templates.ListReport","options":{"settings":{"contextPath":"/CustomerArticleSummary","loadDataOnAppLaunch":true,"autoBind":true,"fitContainer":true,"initialLoad":"Enabled","variantManagement":"Page","navigation":{"CustomerArticleSummary":{"detail":{"route":"CustomerArticleSummaryObjectPage"}}},"controlConfiguration":{"@com.sap.vocabularies.UI.v1.LineItem":{"tableSettings":{"type":"ResposiveTable"}}}}}},"CustomerArticleSummaryObjectPage":{"type":"Component","id":"CustomerArticleSummaryObjectPage","name":"sap.fe.templates.ObjectPage","options":{"settings":{"editableHeaderContent":true,"simpleHeaderFacets":true,"contextPath":"/CustomerArticleSummary"}}}}}},"sap.fiori":{"registrationIds":[],"archeType":"transactional"}}'
});
//# sourceMappingURL=Component-preload.js.map
